Add InfluxDb
linuxserver/Heimdall-Apps pull request #286
Opened 2021-01-03 16:35 UTC by bion19

2021-01-15 09:55 UTC, milanmeu requested changes
The correct name is `InlfuxDB` please rename `InfluxDb` to `InfluxDB`. It is correct in the app.json description 😃. Change de folder and filenames too.

2021-01-15 09:55 UTC, milanmeu commented on InfluxDb/InfluxDb.php
> +<?php namespace App\SupportedApps\InfluxDb;
The correct name is `InlfuxDB` please rename `InfluxDb` to `InfluxDB`.
```suggestion
<?php namespace App\SupportedApps\InfluxDB;
```

2021-01-15 09:55 UTC, milanmeu commented on InfluxDb/InfluxDb.php
> +class InfluxDb extends \App\SupportedApps {
It is also wrong here.
```suggestion
class InfluxDB extends \App\SupportedApps {
```

2021-01-15 09:55 UTC, milanmeu commented on InfluxDb/app.json
> +    "name": "InfluxDb",
The name here is also wrong. It is correct in the app description.
```suggestion
    "name": "InfluxDB",
```

2021-02-16 04:49 UTC, TheCatLady commented
LGTM!

2021-02-16 04:49 UTC, merged