Zigbee2MQTT
linuxserver/Heimdall-Apps pull request #523
Opened 2022-07-19 02:52 UTC by alanmgomes

Zigbee2MQTT enhanced app

2022-07-27 16:16 UTC, dgibbs64 commented
Please add an icon (preferable svg) thank you

2024-01-24 12:58 UTC, mvdkleijn requested changes
Hi there, new here, working through old PRs. If you're still willing to support this PR: please update it against latest master and work through the review comments I left.

Note: I don't know why people where force-pushing code, that's a big no no IMHO.

If you no longer want this PR, feel free to close it.

2024-01-24 12:58 UTC, mvdkleijn commented on TarTenNinety/app.json
This shouldn't be in here I believe

2024-01-24 12:58 UTC, mvdkleijn commented on zigbeemqtt/zigbee2mqtt.png
This icon is way to big. Please read through https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements

hint: 250x250 & tinypng

2024-01-30 10:53 UTC, mvdkleijn commented
As this is from pre-2023 and no replies were made since my initial comment, I'm closing this under the assumption this will no longer be worked on. Feel free to leave a comment so we can re-open the PR if needed.

2024-01-30 10:53 UTC, closed without merging