Add scrypted enhanced app
linuxserver/Heimdall-Apps pull request #600
Opened 2023-03-02 11:00 UTC by 3nigma71

2023-03-07 12:04 UTC, keriati commented
**Running Tests**

Testing Scrypted
Failed: should have an icon file
Icon is too small: { width: 0, height: 0 }

Testing Scrypted
Failed: should have an Icon with min width 100px and min height 100px when PNG

Some Tests Failed!
Error: Process completed with exit code 1.

2023-06-17 09:56 UTC, Rygle commented
![scrypted](https://github.com/linuxserver/Heimdall-Apps/assets/38778536/9457e4c1-11ea-47a0-8828-8a6d9038d6df)
![Scrypted 256x256 tinypng](https://github.com/linuxserver/Heimdall-Apps/assets/38778536/573623bc-423c-42cc-9370-6bb8e54113cc)

2024-02-10 13:48 UTC, mvdkleijn requested changes

2024-02-10 13:48 UTC, mvdkleijn commented on Scrypted/Scrypted.php
> +        $res = parent::execute($this->url('status'));
Is this the actual endpoint? Looks like the actual retrieval of livestats isn't implemented.

2024-02-10 13:48 UTC, mvdkleijn commented on Scrypted/app.json
> +    "icon": "scrypted.png"
Icon missing. It is required. SVG format preferred.

2024-02-10 13:48 UTC, mvdkleijn commented on Scrypted/app.json
> +    "description": "Integration platform",
That description is a little too small IMHO.

2024-02-10 13:48 UTC, mvdkleijn commented on Scrypted/livestats.blade.php
> +<ul class="livestats">
I don't think scrypted has a queue size and speed? Again, this looks like a copy-paste and unimplemented.

2024-02-16 07:35 UTC, mvdkleijn commented
Closing this PR since it looks like an unimplemented copy of the dev templates for an enhanced app.

Also:
- no reaction from pr owner
- no icon
- no real description

2024-02-16 07:35 UTC, closed without merging