Added Ubiquiti
linuxserver/Heimdall-Apps pull request #636
Opened 2023-06-15 12:28 UTC by marcolino7

Added Ubiquiti

2023-06-17 04:47 UTC, Rygle commented
Icons in the prescribed format.

![ubiquiti 256x256 tinypng](https://github.com/linuxserver/Heimdall-Apps/assets/38778536/d01245c9-c1fa-41a6-bfcd-51e1f8d85e37)
![ubiquiti!](https://github.com/linuxserver/Heimdall-Apps/assets/38778536/13fe09ea-c88a-4f29-89c0-bb6e8527b75b)

2024-01-23 13:44 UTC, mvdkleijn requested changes
Icon file is missing. An icon file in either SVG or PNG format is required.
Please see:

- https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
- https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements

2024-01-23 13:51 UTC, mvdkleijn commented on Ubiquiti/app.json
> +    "website": "NA",
This should probably be something like: https://ui.com

2024-01-23 13:51 UTC, mvdkleijn commented on Ubiquiti/app.json
> +    "license": "BSD Zero Clause License",
Ubiquiti is BSD?!?

2024-01-23 13:51 UTC, mvdkleijn commented on Ubiquiti/app.json
> +    "name": "Ubiquiti",
Is this entry for their Unifi UI? Maybe a more specific name would be good.

2024-01-23 13:51 UTC, mvdkleijn commented on Ubiquiti/app.json
> +    "description": "Need to update the \"Unifi\" listing to the modern Ubiquiti logo and change to Dark to make it look nicer :)",
Please describe the product / app.

2024-01-23 13:52 UTC, mvdkleijn commented
Please note that there is already a Unifi app, so not sure why you're trying to add a "Ubiquiti" one.

2024-02-16 09:26 UTC, mvdkleijn commented
- no icon
- metadata issues
- linting issues
- no reply from PR owner

closing to cleanup, feel free to comment / reopen when desired

2024-02-16 09:26 UTC, closed without merging