Add longhorn
linuxserver/Heimdall-Apps pull request #655
Opened 2023-09-17 15:57 UTC by kevinlutzer

2023-12-27 11:04 UTC, Argevollen requested changes
missing icon file

2023-12-27 11:07 UTC, Argevollen approved these changes

2024-01-23 09:57 UTC, mvdkleijn requested changes
Icon file is missing. An icon file is required. Please see:

- https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
- https://github.com/linuxserver/Heimdall-Apps/wiki/Image-requirements

2024-02-16 09:16 UTC, closed without merging

2024-09-04 03:26 UTC, kevinlutzer commented
@mvdkleijn I added the png