Add Zigbee2mqtt Enhanced App
linuxserver/Heimdall-Apps pull request #665
Opened 2024-01-05 16:24 UTC by imchrichri

2024-01-24 17:29 UTC, Argevollen requested changes
This template needs an implementation still!

2024-01-24 17:46 UTC, mvdkleijn requested changes

2024-01-24 17:46 UTC, mvdkleijn commented on zigbeemqtt/zigbeemqtt.php
> +        $res = parent::execute($this->url('status'));
This feels like a copy-n-paste effort without actually implementing any functionality.

Unless you meant to target the `status` endpoint of `url`? Though I doubt that exists in the context of this app.

2024-02-16 09:24 UTC, mvdkleijn commented
- no icon
- no actual enhanced implementation
- no reply from PR owner

closing to cleanup, feel free to comment / reopen when desired

2024-02-16 09:24 UTC, closed without merging